# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'TreasureChestSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TreasureChestSwiftDemo
#  pod 'FMDB'
#  pod 'Masonry'
  #  pod 'SDWebImage', '~> 3.7.5'
  #  pod 'AFNetworking'
  #  pod 'MJExtension'
  #  pod 'ReactiveObjC', '3.1.0'
  #  pod 'MSWeakTimer', '~> 1.1.0'
  #  pod 'MJRefresh', '3.2.0'
  #  pod 'lottie-ios'

  target 'TreasureChestSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
